
all:
	@gcc middleman.c -o middleman.out
	@make -s -C ../__my_srcs all > /dev/null

bonus:
	@gcc middleman.c -o middleman.out
	@make -s -C ../__my_srcs bonus > /dev/null

fclean:
	@make -s -C ../__my_srcs fclean > /dev/null